/**
 * id - autogenerated
 * name
 * password
 * email
 * date of joining - timestamp
 * rating
 * number of matches
 */
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const UserSchema = new Schema(
	{
		username: {
			type: String,
			required: true,
			unique: true,
		},
		password: {
			type: String,
			required: true,
			unique: true,
		},
		email: {
			type: String,
			required: true,
			unique: true,
		},
		rating: {
			type: Number,
			required: false,
			default: 400,
		},
		number_of_matches: {
			type: Number,
			required: false,
			default: 0,
		},
	},
	{
		timestamps: true,
	}
);

const User = mongoose.model("User", UserSchema);

module.exports = User;
